{% set name = "plugcli" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plugcli-{{ version }}.tar.gz
  sha256: 91aa092cbc29e12a933b5b4b9cac354fc6b5c412fdd82747a820e346893ba2ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - click
    - python >={{ python_min }}

test:
  imports:
    - plugcli
    - plugcli.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dwhswenson/plugcli
  summary: Plugin based CLI framework built on click
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dwhswenson
